// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my_array.proto

package com.github.myutman.java;

public final class MyArrayProtos {
  private MyArrayProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MyArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:array.MyArray)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 size = 1;</code>
     */
    boolean hasSize();
    /**
     * <code>required int32 size = 1;</code>
     */
    int getSize();

    /**
     * <code>repeated int32 base = 2;</code>
     */
    java.util.List<java.lang.Integer> getBaseList();
    /**
     * <code>repeated int32 base = 2;</code>
     */
    int getBaseCount();
    /**
     * <code>repeated int32 base = 2;</code>
     */
    int getBase(int index);

    /**
     * <code>optional int64 query_time = 3;</code>
     */
    boolean hasQueryTime();
    /**
     * <code>optional int64 query_time = 3;</code>
     */
    long getQueryTime();

    /**
     * <code>optional int64 client_time = 4;</code>
     */
    boolean hasClientTime();
    /**
     * <code>optional int64 client_time = 4;</code>
     */
    long getClientTime();
  }
  /**
   * Protobuf type {@code array.MyArray}
   */
  public static final class MyArray extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:array.MyArray)
      MyArrayOrBuilder {
    // Use MyArray.newBuilder() to construct.
    private MyArray(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MyArray(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MyArray defaultInstance;
    public static MyArray getDefaultInstance() {
      return defaultInstance;
    }

    public MyArray getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MyArray(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              size_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                base_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              base_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                base_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                base_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              queryTime_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              clientTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          base_ = java.util.Collections.unmodifiableList(base_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.myutman.java.MyArrayProtos.internal_static_array_MyArray_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.myutman.java.MyArrayProtos.internal_static_array_MyArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.myutman.java.MyArrayProtos.MyArray.class, com.github.myutman.java.MyArrayProtos.MyArray.Builder.class);
    }

    public static com.google.protobuf.Parser<MyArray> PARSER =
        new com.google.protobuf.AbstractParser<MyArray>() {
      public MyArray parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyArray(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MyArray> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SIZE_FIELD_NUMBER = 1;
    private int size_;
    /**
     * <code>required int32 size = 1;</code>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 size = 1;</code>
     */
    public int getSize() {
      return size_;
    }

    public static final int BASE_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> base_;
    /**
     * <code>repeated int32 base = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getBaseList() {
      return base_;
    }
    /**
     * <code>repeated int32 base = 2;</code>
     */
    public int getBaseCount() {
      return base_.size();
    }
    /**
     * <code>repeated int32 base = 2;</code>
     */
    public int getBase(int index) {
      return base_.get(index);
    }

    public static final int QUERY_TIME_FIELD_NUMBER = 3;
    private long queryTime_;
    /**
     * <code>optional int64 query_time = 3;</code>
     */
    public boolean hasQueryTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 query_time = 3;</code>
     */
    public long getQueryTime() {
      return queryTime_;
    }

    public static final int CLIENT_TIME_FIELD_NUMBER = 4;
    private long clientTime_;
    /**
     * <code>optional int64 client_time = 4;</code>
     */
    public boolean hasClientTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 client_time = 4;</code>
     */
    public long getClientTime() {
      return clientTime_;
    }

    private void initFields() {
      size_ = 0;
      base_ = java.util.Collections.emptyList();
      queryTime_ = 0L;
      clientTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, size_);
      }
      for (int i = 0; i < base_.size(); i++) {
        output.writeInt32(2, base_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(3, queryTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(4, clientTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, size_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < base_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(base_.get(i));
        }
        size += dataSize;
        size += 1 * getBaseList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, queryTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, clientTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.myutman.java.MyArrayProtos.MyArray prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code array.MyArray}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:array.MyArray)
        com.github.myutman.java.MyArrayProtos.MyArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.myutman.java.MyArrayProtos.internal_static_array_MyArray_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.myutman.java.MyArrayProtos.internal_static_array_MyArray_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.myutman.java.MyArrayProtos.MyArray.class, com.github.myutman.java.MyArrayProtos.MyArray.Builder.class);
      }

      // Construct using com.github.myutman.java.MyArrayProtos.MyArray.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        size_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        base_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        queryTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        clientTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.myutman.java.MyArrayProtos.internal_static_array_MyArray_descriptor;
      }

      public com.github.myutman.java.MyArrayProtos.MyArray getDefaultInstanceForType() {
        return com.github.myutman.java.MyArrayProtos.MyArray.getDefaultInstance();
      }

      public com.github.myutman.java.MyArrayProtos.MyArray build() {
        com.github.myutman.java.MyArrayProtos.MyArray result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.myutman.java.MyArrayProtos.MyArray buildPartial() {
        com.github.myutman.java.MyArrayProtos.MyArray result = new com.github.myutman.java.MyArrayProtos.MyArray(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.size_ = size_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          base_ = java.util.Collections.unmodifiableList(base_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.base_ = base_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.queryTime_ = queryTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.clientTime_ = clientTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.myutman.java.MyArrayProtos.MyArray) {
          return mergeFrom((com.github.myutman.java.MyArrayProtos.MyArray)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.myutman.java.MyArrayProtos.MyArray other) {
        if (other == com.github.myutman.java.MyArrayProtos.MyArray.getDefaultInstance()) return this;
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (!other.base_.isEmpty()) {
          if (base_.isEmpty()) {
            base_ = other.base_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBaseIsMutable();
            base_.addAll(other.base_);
          }
          onChanged();
        }
        if (other.hasQueryTime()) {
          setQueryTime(other.getQueryTime());
        }
        if (other.hasClientTime()) {
          setClientTime(other.getClientTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSize()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.myutman.java.MyArrayProtos.MyArray parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.myutman.java.MyArrayProtos.MyArray) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int size_ ;
      /**
       * <code>required int32 size = 1;</code>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 size = 1;</code>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>required int32 size = 1;</code>
       */
      public Builder setSize(int value) {
        bitField0_ |= 0x00000001;
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 size = 1;</code>
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        size_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> base_ = java.util.Collections.emptyList();
      private void ensureBaseIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          base_ = new java.util.ArrayList<java.lang.Integer>(base_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 base = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getBaseList() {
        return java.util.Collections.unmodifiableList(base_);
      }
      /**
       * <code>repeated int32 base = 2;</code>
       */
      public int getBaseCount() {
        return base_.size();
      }
      /**
       * <code>repeated int32 base = 2;</code>
       */
      public int getBase(int index) {
        return base_.get(index);
      }
      /**
       * <code>repeated int32 base = 2;</code>
       */
      public Builder setBase(
          int index, int value) {
        ensureBaseIsMutable();
        base_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 base = 2;</code>
       */
      public Builder addBase(int value) {
        ensureBaseIsMutable();
        base_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 base = 2;</code>
       */
      public Builder addAllBase(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureBaseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, base_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 base = 2;</code>
       */
      public Builder clearBase() {
        base_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private long queryTime_ ;
      /**
       * <code>optional int64 query_time = 3;</code>
       */
      public boolean hasQueryTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 query_time = 3;</code>
       */
      public long getQueryTime() {
        return queryTime_;
      }
      /**
       * <code>optional int64 query_time = 3;</code>
       */
      public Builder setQueryTime(long value) {
        bitField0_ |= 0x00000004;
        queryTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 query_time = 3;</code>
       */
      public Builder clearQueryTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        queryTime_ = 0L;
        onChanged();
        return this;
      }

      private long clientTime_ ;
      /**
       * <code>optional int64 client_time = 4;</code>
       */
      public boolean hasClientTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 client_time = 4;</code>
       */
      public long getClientTime() {
        return clientTime_;
      }
      /**
       * <code>optional int64 client_time = 4;</code>
       */
      public Builder setClientTime(long value) {
        bitField0_ |= 0x00000008;
        clientTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 client_time = 4;</code>
       */
      public Builder clearClientTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        clientTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:array.MyArray)
    }

    static {
      defaultInstance = new MyArray(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:array.MyArray)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_array_MyArray_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_array_MyArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016my_array.proto\022\005array\"N\n\007MyArray\022\014\n\004si" +
      "ze\030\001 \002(\005\022\014\n\004base\030\002 \003(\005\022\022\n\nquery_time\030\003 \001" +
      "(\003\022\023\n\013client_time\030\004 \001(\003B(\n\027com.github.my" +
      "utman.javaB\rMyArrayProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_array_MyArray_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_array_MyArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_array_MyArray_descriptor,
        new java.lang.String[] { "Size", "Base", "QueryTime", "ClientTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
