// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my_array.proto

package com.github.myutman.java;

public final class MyArrayProtos {
  private MyArrayProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:array.MyArray)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 size = 1;</code>
     */
    boolean hasSize();
    /**
     * <code>required int32 size = 1;</code>
     */
    int getSize();

    /**
     * <code>repeated int32 base = 2;</code>
     */
    java.util.List<java.lang.Integer> getBaseList();
    /**
     * <code>repeated int32 base = 2;</code>
     */
    int getBaseCount();
    /**
     * <code>repeated int32 base = 2;</code>
     */
    int getBase(int index);
  }
  /**
   * Protobuf type {@code array.MyArray}
   */
  public  static final class MyArray extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:array.MyArray)
      MyArrayOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyArray.newBuilder() to construct.
    private MyArray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyArray() {
      size_ = 0;
      base_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyArray(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              size_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                base_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              base_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                base_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                base_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          base_ = java.util.Collections.unmodifiableList(base_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.myutman.java.MyArrayProtos.internal_static_array_MyArray_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.myutman.java.MyArrayProtos.internal_static_array_MyArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.myutman.java.MyArrayProtos.MyArray.class, com.github.myutman.java.MyArrayProtos.MyArray.Builder.class);
    }

    private int bitField0_;
    public static final int SIZE_FIELD_NUMBER = 1;
    private int size_;
    /**
     * <code>required int32 size = 1;</code>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 size = 1;</code>
     */
    public int getSize() {
      return size_;
    }

    public static final int BASE_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> base_;
    /**
     * <code>repeated int32 base = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getBaseList() {
      return base_;
    }
    /**
     * <code>repeated int32 base = 2;</code>
     */
    public int getBaseCount() {
      return base_.size();
    }
    /**
     * <code>repeated int32 base = 2;</code>
     */
    public int getBase(int index) {
      return base_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, size_);
      }
      for (int i = 0; i < base_.size(); i++) {
        output.writeInt32(2, base_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, size_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < base_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(base_.get(i));
        }
        size += dataSize;
        size += 1 * getBaseList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.myutman.java.MyArrayProtos.MyArray)) {
        return super.equals(obj);
      }
      com.github.myutman.java.MyArrayProtos.MyArray other = (com.github.myutman.java.MyArrayProtos.MyArray) obj;

      boolean result = true;
      result = result && (hasSize() == other.hasSize());
      if (hasSize()) {
        result = result && (getSize()
            == other.getSize());
      }
      result = result && getBaseList()
          .equals(other.getBaseList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSize()) {
        hash = (37 * hash) + SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getSize();
      }
      if (getBaseCount() > 0) {
        hash = (37 * hash) + BASE_FIELD_NUMBER;
        hash = (53 * hash) + getBaseList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.myutman.java.MyArrayProtos.MyArray parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.myutman.java.MyArrayProtos.MyArray prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code array.MyArray}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:array.MyArray)
        com.github.myutman.java.MyArrayProtos.MyArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.myutman.java.MyArrayProtos.internal_static_array_MyArray_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.myutman.java.MyArrayProtos.internal_static_array_MyArray_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.myutman.java.MyArrayProtos.MyArray.class, com.github.myutman.java.MyArrayProtos.MyArray.Builder.class);
      }

      // Construct using com.github.myutman.java.MyArrayProtos.MyArray.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        size_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        base_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.myutman.java.MyArrayProtos.internal_static_array_MyArray_descriptor;
      }

      public com.github.myutman.java.MyArrayProtos.MyArray getDefaultInstanceForType() {
        return com.github.myutman.java.MyArrayProtos.MyArray.getDefaultInstance();
      }

      public com.github.myutman.java.MyArrayProtos.MyArray build() {
        com.github.myutman.java.MyArrayProtos.MyArray result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.myutman.java.MyArrayProtos.MyArray buildPartial() {
        com.github.myutman.java.MyArrayProtos.MyArray result = new com.github.myutman.java.MyArrayProtos.MyArray(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.size_ = size_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          base_ = java.util.Collections.unmodifiableList(base_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.base_ = base_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.myutman.java.MyArrayProtos.MyArray) {
          return mergeFrom((com.github.myutman.java.MyArrayProtos.MyArray)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.myutman.java.MyArrayProtos.MyArray other) {
        if (other == com.github.myutman.java.MyArrayProtos.MyArray.getDefaultInstance()) return this;
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (!other.base_.isEmpty()) {
          if (base_.isEmpty()) {
            base_ = other.base_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureBaseIsMutable();
            base_.addAll(other.base_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSize()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.myutman.java.MyArrayProtos.MyArray parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.myutman.java.MyArrayProtos.MyArray) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int size_ ;
      /**
       * <code>required int32 size = 1;</code>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 size = 1;</code>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>required int32 size = 1;</code>
       */
      public Builder setSize(int value) {
        bitField0_ |= 0x00000001;
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 size = 1;</code>
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        size_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> base_ = java.util.Collections.emptyList();
      private void ensureBaseIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          base_ = new java.util.ArrayList<java.lang.Integer>(base_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 base = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getBaseList() {
        return java.util.Collections.unmodifiableList(base_);
      }
      /**
       * <code>repeated int32 base = 2;</code>
       */
      public int getBaseCount() {
        return base_.size();
      }
      /**
       * <code>repeated int32 base = 2;</code>
       */
      public int getBase(int index) {
        return base_.get(index);
      }
      /**
       * <code>repeated int32 base = 2;</code>
       */
      public Builder setBase(
          int index, int value) {
        ensureBaseIsMutable();
        base_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 base = 2;</code>
       */
      public Builder addBase(int value) {
        ensureBaseIsMutable();
        base_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 base = 2;</code>
       */
      public Builder addAllBase(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureBaseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, base_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 base = 2;</code>
       */
      public Builder clearBase() {
        base_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:array.MyArray)
    }

    // @@protoc_insertion_point(class_scope:array.MyArray)
    private static final com.github.myutman.java.MyArrayProtos.MyArray DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.myutman.java.MyArrayProtos.MyArray();
    }

    public static com.github.myutman.java.MyArrayProtos.MyArray getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MyArray>
        PARSER = new com.google.protobuf.AbstractParser<MyArray>() {
      public MyArray parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyArray(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyArray> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyArray> getParserForType() {
      return PARSER;
    }

    public com.github.myutman.java.MyArrayProtos.MyArray getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_array_MyArray_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_array_MyArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016my_array.proto\022\005array\"%\n\007MyArray\022\014\n\004si" +
      "ze\030\001 \002(\005\022\014\n\004base\030\002 \003(\005B(\n\027com.github.myu" +
      "tman.javaB\rMyArrayProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_array_MyArray_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_array_MyArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_array_MyArray_descriptor,
        new java.lang.String[] { "Size", "Base", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
